// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeVision.APIEF.Models;

[Table("T_Attore")]
public partial class TAttore
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }

    [StringLength(100)]
    public string Cognome { get; set; }

    [StringLength(3)]
    public string Nazionalita { get; set; }

    public DateOnly? DataDiNascita { get; set; }

    public bool? IsPremiato { get; set; }

    [InverseProperty("Attore")]
    public virtual ICollection<TRelAttoreOpera> TRelAttoreOperas { get; set; } = new List<TRelAttoreOpera>();
}