// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeVision.APIEF.Models;

[Table("T_Recensione")]
public partial class TRecensione
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(300)]
    public string Descrizione { get; set; }

    public int? Stelle { get; set; }

    public DateOnly? Data { get; set; }

    [StringLength(100)]
    public string Titolo { get; set; }

    [Column("ProfiloID")]
    public int? ProfiloId { get; set; }

    [Column("EpisodioID")]
    public int? EpisodioId { get; set; }

    [Column("StagioneID")]
    public int? StagioneId { get; set; }

    [Column("SerieID")]
    public int? SerieId { get; set; }

    [Column("FilmID")]
    public int? FilmId { get; set; }

    [Column("DocID")]
    public int? DocId { get; set; }

    [ForeignKey("DocId")]
    [InverseProperty("TRecensiones")]
    public virtual TDocumentario Doc { get; set; }

    [ForeignKey("EpisodioId")]
    [InverseProperty("TRecensiones")]
    public virtual TEpisodio Episodio { get; set; }

    [ForeignKey("FilmId")]
    [InverseProperty("TRecensiones")]
    public virtual TFilm Film { get; set; }

    [ForeignKey("ProfiloId")]
    [InverseProperty("TRecensiones")]
    public virtual TProfilo Profilo { get; set; }

    [ForeignKey("SerieId")]
    [InverseProperty("TRecensiones")]
    public virtual TSerie Serie { get; set; }

    [ForeignKey("StagioneId")]
    [InverseProperty("TRecensiones")]
    public virtual TStagione Stagione { get; set; }
}