// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeVision.APIEF.Models;

[Table("T_RelAttoreOpera")]
public partial class TRelAttoreOpera
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("AttoreID")]
    public int? AttoreId { get; set; }

    [Column("FilmID")]
    public int? FilmId { get; set; }

    [Column("SerieID")]
    public int? SerieId { get; set; }

    [ForeignKey("AttoreId")]
    [InverseProperty("TRelAttoreOperas")]
    public virtual TAttore Attore { get; set; }

    [ForeignKey("FilmId")]
    [InverseProperty("TRelAttoreOperas")]
    public virtual TFilm Film { get; set; }

    [ForeignKey("SerieId")]
    [InverseProperty("TRelAttoreOperas")]
    public virtual TSerie Serie { get; set; }
}