// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeVision.APIEF.Models;

[Table("T_Stagione")]
public partial class TStagione
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int? NumeroStagione { get; set; }

    [StringLength(300)]
    public string Descrizione { get; set; }

    [Column("SerieID")]
    public int? SerieId { get; set; }

    public int? Episodi { get; set; }

    [ForeignKey("SerieId")]
    [InverseProperty("TStagiones")]
    public virtual TSerie Serie { get; set; }

    [InverseProperty("Stagione")]
    public virtual ICollection<TEpisodio> TEpisodios { get; set; } = new List<TEpisodio>();

    [InverseProperty("Stagione")]
    public virtual ICollection<TRecensione> TRecensiones { get; set; } = new List<TRecensione>();
}