// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PrimeVision.API.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PrimeVision.API.Models
{
    public partial interface IPrimeVisionContextProcedures
    {
        Task<int> AggiungiAttoreAsync(string Nome, string Cognome, string Nazionalita, DateTime? DataDiNascita, bool? IsPremiato, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiCronologiaAsync(DateTime? DataVisione, int? ProfiloID, int? EpisodioID, int? FilmID, int? DocID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiDocumentarioAsync(string Titolo, int? Durata, DateTime? DataUscita, int? GenereID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiDurataPianoAsync(DateTime? DataInizio, DateTime? DataFine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiEpisodioAsync(int? Durata, string Titolo, string Descrizione, int? NumeroEpisodio, int? StagioneID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiFilmAsync(string Titolo, int? Durata, DateTime? DataUscita, bool? IsVietato, bool? IsPremiato, int? GenereID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiGenereAsync(string Nome, string Descrizione, bool? IsPopolare, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiLinguaAsync(string Nome, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiPianoAsync(string Nome, string Descrizione, decimal? Costo, int? DurataPianoID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiPreferitoAsync(int? FilmID, int? SerieID, int? ProfiloID, int? DocID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiProfiloAsync(string Nickname, byte[] FotoProfilo, int? UtenteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiRecensioneAsync(string Descrizione, int? Stelle, DateTime? Data, string Titolo, int? ProfiloID, int? EpisodioID, int? StagioneID, int? SerieID, int? FilmID, int? DocID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiRegistaAsync(string Nome, string Cognome, DateTime? DataDiNascita, string Nazionalita, int? NumeroOscar, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiSerieAsync(string Titolo, int? Stagioni, DateTime? DataUscita, bool? IsVietato, bool? IsPremiato, int? GenereID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiStagioneAsync(int? NumeroStagione, string Descrizione, int? SerieID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AggiungiUtenteAsync(string Nome, string Cognome, string Indirizzo, string Password, DateTime? DataDiNascita, string Email, string Sesso, string Nazionalita, int? PianoID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
