// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeVision.API.Models;

[Table("T_Episodio")]
public partial class TEpisodio
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int? Durata { get; set; }

    [StringLength(100)]
    public string Titolo { get; set; }

    [StringLength(300)]
    public string Descrizione { get; set; }

    public int? NumeroEpisodio { get; set; }

    [Column("StagioneID")]
    public int? StagioneId { get; set; }

    [ForeignKey("StagioneId")]
    [InverseProperty("TEpisodios")]
    public virtual TStagione Stagione { get; set; }

    [InverseProperty("Episodio")]
    public virtual ICollection<TCronologia> TCronologia { get; set; } = new List<TCronologia>();

    [InverseProperty("Episodio")]
    public virtual ICollection<TRecensione> TRecensiones { get; set; } = new List<TRecensione>();

    [InverseProperty("Episodio")]
    public virtual ICollection<TRelLinguaOpera> TRelLinguaOperas { get; set; } = new List<TRelLinguaOpera>();
}