// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeVision.API.Models;

[Table("T_Genere")]
public partial class TGenere
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }

    [StringLength(300)]
    public string Descrizione { get; set; }

    public bool? IsPopolare { get; set; }

    [InverseProperty("Genere")]
    public virtual ICollection<TDocumentario> TDocumentarios { get; set; } = new List<TDocumentario>();

    [InverseProperty("Genere")]
    public virtual ICollection<TFilm> TFilms { get; set; } = new List<TFilm>();

    [InverseProperty("Genere")]
    public virtual ICollection<TSerie> TSeries { get; set; } = new List<TSerie>();
}