// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeVision.API.Models;

[Table("T_Utente")]
public partial class TUtente
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }

    [StringLength(100)]
    public string Cognome { get; set; }

    [StringLength(200)]
    public string Indirizzo { get; set; }

    [StringLength(16)]
    public string Password { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DataDiNascita { get; set; }

    [StringLength(200)]
    public string Email { get; set; }

    [StringLength(5)]
    public string Sesso { get; set; }

    [StringLength(3)]
    public string Nazionalita { get; set; }

    [Column("PianoID")]
    public int? PianoId { get; set; }

    [ForeignKey("PianoId")]
    [InverseProperty("TUtentes")]
    public virtual TPiano Piano { get; set; }

    [InverseProperty("Utente")]
    public virtual ICollection<TProfilo> TProfilos { get; set; } = new List<TProfilo>();
}