// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using PrimeVision.APIEF.Models;

namespace CLCommon.Models;

[Table("T_Cronologia")]
public partial class TCronologium
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public DateOnly? DataVisione { get; set; }

    [Column("ProfiloID")]
    public int? ProfiloId { get; set; }

    [Column("EpisodioID")]
    public int? EpisodioId { get; set; }

    [Column("FilmID")]
    public int? FilmId { get; set; }

    [Column("DocID")]
    public int? DocId { get; set; }

    [ForeignKey("DocId")]
    [InverseProperty("TCronologia")]
    public virtual TDocumentario Doc { get; set; }

    [ForeignKey("EpisodioId")]
    [InverseProperty("TCronologia")]
    public virtual TEpisodio Episodio { get; set; }

    [ForeignKey("FilmId")]
    [InverseProperty("TCronologia")]
    public virtual TFilm Film { get; set; }

    [ForeignKey("ProfiloId")]
    [InverseProperty("TCronologia")]
    public virtual TProfilo Profilo { get; set; }
}