// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using PrimeVision.APIEF.Models;

namespace CLCommon.Models;

[Table("T_Film")]
public partial class TFilm
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Titolo { get; set; }

    public int? Durata { get; set; }

    public DateOnly? DataUscita { get; set; }

    public bool? IsVietato { get; set; }

    public bool? IsPremiato { get; set; }

    [Column("GenereID")]
    public int? GenereId { get; set; }

    [ForeignKey("GenereId")]
    [InverseProperty("TFilms")]
    public virtual TGenere Genere { get; set; }

    [StringLength(200)]
    public string Locandina { get; set; }

    [InverseProperty("Film")]
    public virtual ICollection<TCronologium> TCronologia { get; set; } = new List<TCronologium>();

    [InverseProperty("Film")]
    public virtual ICollection<TPreferito> TPreferitos { get; set; } = new List<TPreferito>();

    [InverseProperty("Film")]
    public virtual ICollection<TRecensione> TRecensiones { get; set; } = new List<TRecensione>();

    [InverseProperty("Film")]
    public virtual ICollection<TRelAttoreOpera> TRelAttoreOperas { get; set; } = new List<TRelAttoreOpera>();

    [InverseProperty("Film")]
    public virtual ICollection<TRelLinguaOpera> TRelLinguaOperas { get; set; } = new List<TRelLinguaOpera>();

    [InverseProperty("Film")]
    public virtual ICollection<TRelRegistaOpera> TRelRegistaOperas { get; set; } = new List<TRelRegistaOpera>();
}