// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using PrimeVision.APIEF.Models;

namespace CLCommon.Models;

[Table("T_Piano")]
public partial class TPiano
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }

    [StringLength(300)]
    public string Descrizione { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Costo { get; set; }

    [Column("DurataPianoID")]
    public int? DurataPianoId { get; set; }

    [ForeignKey("DurataPianoId")]
    [InverseProperty("TPianos")]
    public virtual TDurataPiano DurataPiano { get; set; }
}