// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using PrimeVision.APIEF.Models;

namespace CLCommon.Models;

[Table("T_Regista")]
public partial class TRegistum
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }

    [StringLength(100)]
    public string Cognome { get; set; }

    public DateOnly? DataDiNascita { get; set; }

    [StringLength(3)]
    public string Nazionalita { get; set; }

    public int? NumeroOscar { get; set; }

    [InverseProperty("Regista")]
    public virtual ICollection<TRelRegistaOpera> TRelRegistaOperas { get; set; } = new List<TRelRegistaOpera>();
}