// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using PrimeVision.APIEF.Models;

namespace CLCommon.Models;

[Table("T_Serie")]
public partial class TSerie
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Titolo { get; set; }

    public int? Stagioni { get; set; }

    public DateOnly? DataUscita { get; set; }

    public bool? IsVietato { get; set; }

    public bool? IsPremiato { get; set; }

    [Column("GenereID")]
    public int? GenereId { get; set; }

    [ForeignKey("GenereId")]
    [InverseProperty("TSeries")]
    public virtual TGenere Genere { get; set; }

    [InverseProperty("Serie")]
    public virtual ICollection<TPreferito> TPreferitos { get; set; } = new List<TPreferito>();

    [InverseProperty("Serie")]
    public virtual ICollection<TRecensione> TRecensiones { get; set; } = new List<TRecensione>();

    [InverseProperty("Serie")]
    public virtual ICollection<TRelAttoreOpera> TRelAttoreOperas { get; set; } = new List<TRelAttoreOpera>();

    [InverseProperty("Serie")]
    public virtual ICollection<TRelRegistaOpera> TRelRegistaOperas { get; set; } = new List<TRelRegistaOpera>();

    [InverseProperty("Serie")]
    public virtual ICollection<TStagione> TStagiones { get; set; } = new List<TStagione>();
}