// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CLCommon.ModelsMOME;

[Table("T_Film")]
public partial class TFilm
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Titolo { get; set; }

    public int? Durata { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DataUscita { get; set; }

    public bool? IsVietato { get; set; }

    public bool? IsPremiato { get; set; }

    [Column("GenereID")]
    public int? GenereId { get; set; }

    [StringLength(200)]
    public string Locandina { get; set; }
}